// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkingwithSQLLiteinAsp.NETCoreWebAPI.ApplicationDbContext;

#nullable disable

namespace WorkingwithSQLLiteinAsp.NETCoreWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Commitment", b =>
                {
                    b.Property<int>("CommitmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommitmentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentAssetClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentCurrency")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommitmentID1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvestorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommitmentID");

                    b.HasIndex("CommitmentID1");

                    b.HasIndex("InvestorId");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("Investor", b =>
                {
                    b.Property<int>("InvestorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvestorCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvestorDateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvestorLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvestorId");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("Commitment", b =>
                {
                    b.HasOne("Commitment", null)
                        .WithMany("CommitmentsDetails")
                        .HasForeignKey("CommitmentID1");

                    b.HasOne("Investor", null)
                        .WithMany("Commitments")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Commitment", b =>
                {
                    b.Navigation("CommitmentsDetails");
                });

            modelBuilder.Entity("Investor", b =>
                {
                    b.Navigation("Commitments");
                });
#pragma warning restore 612, 618
        }
    }
}
